# Basic functions

In [1]:
import numpy as np
arr1=np.array([[3,2,5,7,8],[2,3,4,5,3]])
print(arr1)

[[3 2 5 7 8]
 [2 3 4 5 3]]


In [2]:
arr1.shape

(2, 5)

In [3]:
arr1.dtype

dtype('int32')

In [4]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones(6).dtype

dtype('float64')

In [6]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
arr1

array([[3, 2, 5, 7, 8],
       [2, 3, 4, 5, 3]])

In [8]:
arr1*arr1

array([[ 9,  4, 25, 49, 64],
       [ 4,  9, 16, 25,  9]])

In [9]:
arr1-arr1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
arr1+arr1


array([[ 6,  4, 10, 14, 16],
       [ 4,  6,  8, 10,  6]])

In [11]:
arr1**arr1

array([[      27,        4,     3125,   823543, 16777216],
       [       4,       27,      256,     3125,       27]])

In [12]:
1/arr1

array([[0.33333333, 0.5       , 0.2       , 0.14285714, 0.125     ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.33333333]])

# Slicing

In [13]:
arr2=np.array([2,3,4,5,6,7])

In [14]:
arr=arr2[4:6]

In [15]:
arr3=arr2[4:6].copy()

In [16]:
arr

array([6, 7])

In [18]:
arr[0]=9

In [17]:
arr3[0]=10

In [19]:
arr2

array([2, 3, 4, 5, 9, 7])

In [21]:
arr2

array([2, 3, 4, 5, 9, 7])

In [24]:
arr1

array([[3, 2, 5, 7, 8],
       [2, 3, 4, 5, 3]])

In [25]:
arr1[0]

array([3, 2, 5, 7, 8])

In [26]:
arr1[0,3]

7