In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[2,3,4]])

In [3]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [4]:
a.sum(axis=1)

array([6, 9])

In [5]:
a.sum(axis=0)

array([3, 5, 7])

In [7]:
b=np.array([[3,4,5],[5,6,7]])

In [8]:
a.dot(b.transpose())

array([[ 50,  74],
       [ 74, 110]])

In [9]:
dir()

['In',
 'Out',
 '_',
 '_3',
 '_4',
 '_5',
 '_8',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__session__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'a',
 'b',
 'exit',
 'get_ipython',
 'np',
 'open',
 'quit']

In [10]:
len(dir(np))

593

In [11]:
np.cross(a,b)

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
np.sort(a)

array([[3, 4, 5],
       [5, 6, 7]])

In [13]:
np.sort(a,axis=0)

array([[3, 4, 5],
       [5, 6, 7]])