In [1]:
import numpy as np

In [2]:
a=np.arange(6)


In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [4]:
b=np.array([1,2,3,4,5,6,33,44,5,3,4,2,2,4,5,2,3,5])
c=b.reshape(6,3)

In [5]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [33, 44,  5],
       [ 3,  4,  2],
       [ 2,  4,  5],
       [ 2,  3,  5]])

In [6]:
np.argsort(b)

array([ 0,  1, 15, 12, 11,  2, 16,  9,  3, 13, 10, 14,  8,  4, 17,  5,  6,
        7], dtype=int64)

In [7]:
np.argmin(b)


0

In [8]:
np.argmax(b)

7

In [9]:
np.argsort(c)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1],
       [2, 0, 1],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [10]:
np.argsort(c,axis=0)

array([[0, 0, 3],
       [4, 5, 0],
       [5, 3, 2],
       [3, 4, 4],
       [1, 1, 5],
       [2, 2, 1]], dtype=int64)

In [11]:
"Hello world" 

'Hello world'